# Use MySQL 8.0 as the base image
FROM mysql:8.0

# Copy the initialization script
COPY db/cinema.sql /docker-entrypoint-initdb.d/

# Set permissions
RUN chown -R mysql:mysql /docker-entrypoint-initdb.d/ 